// ===== App Logic =====

document.addEventListener('DOMContentLoaded', () => {
    const { colorPalettes, uiStyles, fontPairings, getRecommendation } = window.designData;

    // DOM Elements
    const themeToggle = document.getElementById('themeToggle');
    const searchInput = document.getElementById('searchInput');
    const searchBtn = document.getElementById('searchBtn');
    const quickTags = document.querySelectorAll('.quick-tag');
    const tabBtns = document.querySelectorAll('.tab-btn');
    const filterBtns = document.querySelectorAll('.filter-btn');
    const recommendationSection = document.getElementById('recommendationSection');
    const closeRecommendation = document.getElementById('closeRecommendation');
    const toast = document.getElementById('toast');

    // Initialize
    initTheme();
    renderPalettes();
    renderStyles();
    renderFonts();
    renderProPalettes();
    renderProStyles();

    // ===== Theme Toggle =====
    function initTheme() {
        const savedTheme = localStorage.getItem('theme') || 'light';
        document.documentElement.setAttribute('data-theme', savedTheme);
        updateThemeIcon(savedTheme);
    }

    function updateThemeIcon(theme) {
        const icon = themeToggle.querySelector('.theme-icon');
        icon.textContent = theme === 'dark' ? '☀️' : '🌙';
    }

    themeToggle.addEventListener('click', () => {
        const currentTheme = document.documentElement.getAttribute('data-theme');
        const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
        document.documentElement.setAttribute('data-theme', newTheme);
        localStorage.setItem('theme', newTheme);
        updateThemeIcon(newTheme);
    });

    // ===== Search & Recommendation =====
    function showRecommendation(topic) {
        const rec = getRecommendation(topic);

        document.getElementById('topicTitle').textContent = rec.topic;

        // Color Palette
        const paletteHtml = rec.palette.colors.map((color, i) =>
            `<div class="color-swatch" style="background: ${color}" data-color="${color}" title="${rec.palette.colorNames[i]}"></div>`
        ).join('');
        document.getElementById('colorPalette').innerHTML = paletteHtml;

        // Font
        const fontHtml = `
            <div class="font-item">
                <div class="font-label">제목 폰트</div>
                <div class="font-name" style="font-family: '${rec.font.heading}', serif">${rec.font.heading}</div>
            </div>
            <div class="font-item">
                <div class="font-label">본문 폰트</div>
                <div class="font-name" style="font-family: '${rec.font.body}', sans-serif">${rec.font.body}</div>
            </div>
        `;
        document.getElementById('fontPreview').innerHTML = fontHtml;

        // Style
        const styleHtml = `
            <span class="style-tag">${rec.style.name}</span>
            <span class="style-tag">${rec.style.nameEn}</span>
        `;
        document.getElementById('stylePreview').innerHTML = styleHtml;

        // Layout
        const layoutHtml = rec.layout.map(item =>
            `<span class="layout-tag">${item}</span>`
        ).join('');
        document.getElementById('layoutPreview').innerHTML = layoutHtml;

        // Tips
        const tipsHtml = `
            <div class="tip-group">
                <h4>✅ 추천 사항</h4>
                <ul>
                    ${rec.tips.map(tip => `<li>${tip}</li>`).join('')}
                </ul>
            </div>
            <div class="tip-group avoid">
                <h4>❌ 피해야 할 것</h4>
                <ul>
                    ${rec.avoid.map(item => `<li>${item}</li>`).join('')}
                </ul>
            </div>
        `;
        document.getElementById('tipsContent').innerHTML = tipsHtml;

        // Copy buttons
        document.getElementById('copyColors').onclick = () => {
            const cssVars = rec.palette.colors.map((color, i) =>
                `--color-${i + 1}: ${color};`
            ).join('\n');
            copyToClipboard(`:root {\n${cssVars}\n}`);
        };

        document.getElementById('copyFonts').onclick = () => {
            copyToClipboard(rec.font.googleUrl);
        };

        // ===== Auto Generate CSS =====
        const autoCSS = generateAutoCSS(rec);
        document.getElementById('autoGeneratedCSS').textContent = autoCSS;

        document.getElementById('copyAutoCSS').onclick = () => {
            copyToClipboard(autoCSS);
        };

        document.getElementById('downloadCSS').onclick = () => {
            downloadCSS(autoCSS, `${rec.topic}-styles.css`);
        };

        // ===== Auto Preview =====
        renderAutoPreview(rec);

        // Device buttons in recommendation section
        const autoDeviceBtns = document.querySelectorAll('.preview-card .device-btn');
        autoDeviceBtns.forEach(btn => {
            btn.addEventListener('click', () => {
                autoDeviceBtns.forEach(b => b.classList.remove('active'));
                btn.classList.add('active');
                const frame = document.getElementById('autoPreviewFrame');
                frame.classList.remove('desktop', 'tablet', 'mobile');
                frame.classList.add(btn.dataset.device);
            });
        });

        document.getElementById('openAutoPreview').onclick = () => {
            const html = generateAutoPreviewHTML(rec);
            const newWindow = window.open('', '_blank');
            newWindow.document.write(html);
            newWindow.document.close();
        };

        // Show section
        recommendationSection.style.display = 'block';
        recommendationSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }

    // ===== Auto CSS Generator =====
    function generateAutoCSS(rec) {
        let css = `/* ===== ${rec.topic} 웹사이트 CSS ===== */\n`;
        css += `/* 자동 생성일: ${new Date().toLocaleString('ko-KR')} */\n\n`;

        // Color Variables
        css += `/* ===== 색상 변수 (${rec.palette.name}) ===== */\n`;
        css += `:root {\n`;
        rec.palette.colors.forEach((color, i) => {
            // 영어 변수명 사용
            const englishNames = ['primary', 'secondary', 'accent', 'text', 'background'];
            css += `    --color-${englishNames[i] || `color-${i + 1}`}: ${color};\n`;
        });
        css += `}\n\n`;

        // Font Import - 올바른 Google Fonts API URL 생성
        css += `/* ===== 폰트 (${rec.font.heading} + ${rec.font.body}) ===== */\n`;
        const headingFont = rec.font.heading.replace(/\s+/g, '+');
        const bodyFont = rec.font.body.replace(/\s+/g, '+');
        const fontUrl = `https://fonts.googleapis.com/css2?family=${headingFont}:wght@400;500;600;700&family=${bodyFont}:wght@300;400;500;600;700&display=swap`;
        css += `@import url('${fontUrl}');\n\n`;
        css += `:root {\n`;
        css += `    --font-heading: '${rec.font.heading}', serif;\n`;
        css += `    --font-body: '${rec.font.body}', sans-serif;\n`;
        css += `}\n\n`;

        // Base Styles
        css += `/* ===== 기본 스타일 ===== */\n`;
        css += `* {\n    margin: 0;\n    padding: 0;\n    box-sizing: border-box;\n}\n\n`;
        css += `body {\n`;
        css += `    font-family: var(--font-body);\n`;
        css += `    background-color: var(--color-background);\n`;
        css += `    color: var(--color-text);\n`;
        css += `    line-height: 1.6;\n`;
        css += `}\n\n`;

        // Headings
        css += `h1, h2, h3, h4, h5, h6 {\n`;
        css += `    font-family: var(--font-heading);\n`;
        css += `    line-height: 1.2;\n`;
        css += `    color: var(--color-primary);\n`;
        css += `}\n\n`;

        // UI Style - 중복 padding 제거
        css += `/* ===== UI 스타일 (${rec.style.name}) ===== */\n`;
        css += `.card {\n`;
        css += `    background: white;\n`;
        css += `    padding: 1.5rem;\n`;
        css += `    border-radius: 12px;\n`;
        css += `    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);\n`;
        css += `}\n\n`;

        // Button Styles
        css += `/* ===== 버튼 스타일 ===== */\n`;
        css += `.btn {\n`;
        css += `    padding: 0.75rem 1.5rem;\n`;
        css += `    border: none;\n`;
        css += `    border-radius: 8px;\n`;
        css += `    font-size: 1rem;\n`;
        css += `    font-weight: 600;\n`;
        css += `    cursor: pointer;\n`;
        css += `    transition: all 0.2s ease;\n`;
        css += `}\n\n`;

        css += `.btn-primary {\n`;
        css += `    background-color: var(--color-primary);\n`;
        css += `    color: white;\n`;
        css += `}\n\n`;

        css += `.btn:hover {\n`;
        css += `    transform: translateY(-2px);\n`;
        css += `    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);\n`;
        css += `}\n\n`;

        // Container
        css += `/* ===== 컨테이너 ===== */\n`;
        css += `.container {\n`;
        css += `    width: 100%;\n`;
        css += `    max-width: 1200px;\n`;
        css += `    margin: 0 auto;\n`;
        css += `    padding: 0 1rem;\n`;
        css += `}\n\n`;

        // Responsive
        css += `/* ===== 반응형 ===== */\n`;
        css += `@media (max-width: 768px) {\n`;
        css += `    .container { padding: 0 0.5rem; }\n`;
        css += `    h1 { font-size: 1.75rem; }\n`;
        css += `    h2 { font-size: 1.5rem; }\n`;
        css += `}\n`;

        return css;
    }

    // ===== Download CSS =====
    function downloadCSS(css, filename) {
        const blob = new Blob([css], { type: 'text/css' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        showToast('CSS 파일이 다운로드되었습니다!');
    }

    // ===== Auto Preview Render =====
    function renderAutoPreview(rec) {
        const previewContent = document.getElementById('autoPreviewContent');
        const palette = rec.palette;
        const font = rec.font;

        const html = `
            <div style="font-family: '${font.body}', sans-serif; background-color: ${palette.colors[4]}; color: ${palette.colors[3]};">
                <div style="background: linear-gradient(135deg, ${palette.colors[0]}, ${palette.colors[1]}); padding: 3rem 2rem; text-align: center;">
                    <h1 style="font-family: '${font.heading}', serif; color: white; font-size: 2rem; margin-bottom: 0.75rem;">${rec.topic} 웹사이트</h1>
                    <p style="color: rgba(255,255,255,0.9); font-size: 1rem; margin-bottom: 1.5rem;">최고의 ${rec.topic} 서비스를 경험하세요</p>
                    <button style="background: white; color: ${palette.colors[0]}; padding: 0.75rem 1.5rem; border: none; border-radius: 8px; font-size: 0.9rem; font-weight: 600; cursor: pointer;">시작하기</button>
                </div>
                <div style="padding: 2rem 1.5rem; display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem;">
                    ${rec.layout.slice(0, 3).map((item, i) => `
                        <div style="background: white; padding: 1.25rem; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);">
                            <h3 style="font-family: '${font.heading}', serif; color: ${palette.colors[0]}; margin-bottom: 0.5rem; font-size: 1rem;">${['✨', '🚀', '💡'][i]} ${item}</h3>
                            <p style="color: ${palette.colors[3]}; opacity: 0.8; font-size: 0.85rem;">${rec.tips[i] || '멋진 기능'}</p>
                        </div>
                    `).join('')}
                </div>
            </div>
        `;
        previewContent.innerHTML = html;
    }

    // ===== Auto Preview HTML (New Window) =====
    function generateAutoPreviewHTML(rec) {
        const palette = rec.palette;
        const font = rec.font;

        return `
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${rec.topic} - 미리보기</title>
    <link href="${font.googleUrl}" rel="stylesheet">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: '${font.body}', sans-serif;
            background: ${palette.colors[4]}; 
            color: ${palette.colors[3]};
            line-height: 1.6;
        }
        h1, h2, h3 { font-family: '${font.heading}', serif; }
    </style>
</head>
<body>
    ${document.getElementById('autoPreviewContent').innerHTML}
</body>
</html>
        `;
    }

    searchBtn.addEventListener('click', () => {
        const topic = searchInput.value.trim();
        if (topic) showRecommendation(topic);
    });

    searchInput.addEventListener('keypress', (e) => {
        if (e.key === 'Enter') {
            const topic = searchInput.value.trim();
            if (topic) showRecommendation(topic);
        }
    });

    quickTags.forEach(tag => {
        tag.addEventListener('click', () => {
            const topic = tag.dataset.topic;
            searchInput.value = topic;
            showRecommendation(topic);
        });
    });

    closeRecommendation.addEventListener('click', () => {
        recommendationSection.style.display = 'none';
    });

    // ===== Tabs =====
    tabBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            tabBtns.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');

            document.querySelectorAll('.tab-content').forEach(content => {
                content.classList.remove('active');
            });

            const tabId = `${btn.dataset.tab}-content`;
            document.getElementById(tabId).classList.add('active');
        });
    });

    // ===== Filters =====
    filterBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            filterBtns.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            renderPalettes(btn.dataset.filter);
        });
    });

    // ===== Render Palettes =====
    function renderPalettes(filter = 'all') {
        const grid = document.getElementById('palettesGrid');
        const filtered = filter === 'all'
            ? colorPalettes
            : colorPalettes.filter(p => p.category === filter);

        grid.innerHTML = filtered.map(palette => `
            <div class="palette-card" data-palette='${JSON.stringify(palette)}'>
                <div class="palette-colors">
                    ${palette.colors.map(color =>
            `<div class="palette-color" style="background: ${color}" data-color="${color}"></div>`
        ).join('')}
                </div>
                <div class="palette-info">
                    <div class="palette-name">${palette.name}</div>
                    <div class="palette-category">${palette.industry.slice(0, 3).join(' · ')}</div>
                </div>
            </div>
        `).join('');

        // Add click handlers
        grid.querySelectorAll('.palette-card').forEach(card => {
            card.addEventListener('click', () => {
                const palette = JSON.parse(card.dataset.palette);
                const cssVars = palette.colors.map((color, i) =>
                    `--${palette.colorNames[i].toLowerCase().replace(/\s+/g, '-')}: ${color};`
                ).join('\n');
                copyToClipboard(`:root {\n${cssVars}\n}`);
            });
        });

        grid.querySelectorAll('.palette-color').forEach(color => {
            color.addEventListener('click', (e) => {
                e.stopPropagation();
                copyToClipboard(color.dataset.color);
            });
        });
    }

    // ===== Render Styles =====
    function renderStyles() {
        const grid = document.getElementById('stylesGrid');

        grid.innerHTML = uiStyles.map(style => {
            let demoStyle = '';
            let bgStyle = `background: ${style.demo.background};`;

            if (style.demo.card) {
                if (style.demo.card.includes('gradient')) {
                    demoStyle = `background: ${style.demo.card};`;
                } else if (style.demo.card.includes('rgba')) {
                    demoStyle = `background: ${style.demo.card}; backdrop-filter: ${style.demo.blur || 'blur(10px)'};`;
                } else {
                    demoStyle = `background: ${style.demo.card};`;
                }
            }

            if (style.demo.shadow) {
                demoStyle += ` box-shadow: ${style.demo.shadow};`;
            }

            if (style.demo.border) {
                demoStyle += ` border: ${style.demo.border};`;
            }

            if (style.demo.radius) {
                demoStyle += ` border-radius: ${style.demo.radius};`;
            }

            if (style.demo.text) {
                demoStyle += ` color: ${style.demo.text};`;
            }

            return `
                <div class="style-card">
                    <div class="style-preview-box" style="${bgStyle}">
                        <div class="style-demo" style="${demoStyle}">
                            ${style.name}
                        </div>
                    </div>
                    <div class="style-info">
                        <div class="style-name">${style.name} <span style="color: var(--text-tertiary); font-weight: 400;">${style.nameEn}</span></div>
                        <div class="style-desc">${style.description}</div>
                        <div class="style-use-cases">
                            ${style.useCases.map(uc => `<span class="use-case">${uc}</span>`).join('')}
                        </div>
                    </div>
                </div>
            `;
        }).join('');

        // Add click handlers to copy CSS
        grid.querySelectorAll('.style-card').forEach((card, i) => {
            card.addEventListener('click', () => {
                copyToClipboard(`/* ${uiStyles[i].name} */\n${uiStyles[i].css}`);
            });
            card.style.cursor = 'pointer';
        });
    }

    // ===== Render Fonts =====
    function renderFonts() {
        const grid = document.getElementById('fontsGrid');

        // Load Google Fonts dynamically
        const fontLinks = fontPairings.map(f =>
            `family=${f.heading.replace(/\s+/g, '+')}:wght@400;700&family=${f.body.replace(/\s+/g, '+')}:wght@400;700`
        ).join('&');

        const link = document.createElement('link');
        link.href = `https://fonts.googleapis.com/css2?${fontLinks}&display=swap`;
        link.rel = 'stylesheet';
        document.head.appendChild(link);

        grid.innerHTML = fontPairings.map(font => `
            <div class="font-card" data-url="${font.googleUrl}">
                <div class="font-heading" style="font-family: '${font.heading}', serif">
                    ${font.heading}
                </div>
                <div class="font-body" style="font-family: '${font.body}', sans-serif">
                    ${font.description}
                </div>
                <div class="font-meta">
                    <div class="font-names">
                        ${font.heading} + ${font.body}
                    </div>
                    <div class="font-mood">${font.mood}</div>
                </div>
            </div>
        `).join('');

        // Add click handlers
        grid.querySelectorAll('.font-card').forEach(card => {
            card.addEventListener('click', () => {
                copyToClipboard(card.dataset.url);
            });
        });
    }

    // ===== Copy to Clipboard =====
    function copyToClipboard(text) {
        navigator.clipboard.writeText(text).then(() => {
            showToast('복사되었습니다!');
        }).catch(() => {
            // Fallback for older browsers
            const textarea = document.createElement('textarea');
            textarea.value = text;
            document.body.appendChild(textarea);
            textarea.select();
            document.execCommand('copy');
            document.body.removeChild(textarea);
            showToast('복사되었습니다!');
        });
    }

    function showToast(message) {
        const toastMsg = toast.querySelector('.toast-message');
        toastMsg.textContent = message;
        toast.classList.add('show');

        setTimeout(() => {
            toast.classList.remove('show');
        }, 2000);
    }

    // ===== Color swatch click in recommendation =====
    document.getElementById('colorPalette').addEventListener('click', (e) => {
        if (e.target.classList.contains('color-swatch')) {
            copyToClipboard(e.target.dataset.color);
        }
    });

    // ===== CSS Generator =====
    initCSSGenerator();

    function initCSSGenerator() {
        const selectPalette = document.getElementById('selectPalette');
        const selectFont = document.getElementById('selectFont');
        const selectStyle = document.getElementById('selectStyle');
        const generateBtn = document.getElementById('generateCSSBtn');
        const copyCSSBtn = document.getElementById('copyCSSBtn');
        const generatedCSS = document.getElementById('generatedCSS');
        const selectedPalettePreview = document.getElementById('selectedPalettePreview');
        const selectedFontPreview = document.getElementById('selectedFontPreview');

        // Populate palette options
        const optGroupBasic = document.createElement('optgroup');
        optGroupBasic.label = '🎨 기본 팔레트';
        colorPalettes.forEach((palette, i) => {
            const option = document.createElement('option');
            option.value = `basic-${i}`;
            option.textContent = `${palette.name} (${palette.industry[0]})`;
            optGroupBasic.appendChild(option);
        });
        selectPalette.appendChild(optGroupBasic);

        // Pro palettes
        if (window.skillData && window.skillData.proColorPalettes) {
            const optGroupPro = document.createElement('optgroup');
            optGroupPro.label = '🏆 Pro 팔레트 (산업별)';
            window.skillData.proColorPalettes.forEach((palette, i) => {
                const option = document.createElement('option');
                option.value = `pro-${i}`;
                option.textContent = `⭐ ${palette.type}`;
                optGroupPro.appendChild(option);
            });
            selectPalette.appendChild(optGroupPro);
        }

        // Populate font options
        const fontOptGroupBasic = document.createElement('optgroup');
        fontOptGroupBasic.label = '✒️ 기본 폰트';
        fontPairings.forEach((font, i) => {
            const option = document.createElement('option');
            option.value = `basic-${i}`;
            option.textContent = `${font.heading} + ${font.body}`;
            fontOptGroupBasic.appendChild(option);
        });
        selectFont.appendChild(fontOptGroupBasic);

        // Pro fonts
        if (window.skillData && window.skillData.proFontPairings) {
            const fontOptGroupPro = document.createElement('optgroup');
            fontOptGroupPro.label = '🏆 Pro 폰트';
            window.skillData.proFontPairings.forEach((font, i) => {
                const option = document.createElement('option');
                option.value = `pro-${i}`;
                option.textContent = `⭐ ${font.name} (${font.heading})`;
                fontOptGroupPro.appendChild(option);
            });
            selectFont.appendChild(fontOptGroupPro);
        }

        // Populate style options
        const styleOptGroupBasic = document.createElement('optgroup');
        styleOptGroupBasic.label = '🖼️ 기본 스타일';
        uiStyles.forEach((style, i) => {
            const option = document.createElement('option');
            option.value = `basic-${i}`;
            option.textContent = `${style.name} (${style.nameEn})`;
            styleOptGroupBasic.appendChild(option);
        });
        selectStyle.appendChild(styleOptGroupBasic);

        // Pro styles
        if (window.skillData && window.skillData.proUIStyles) {
            const styleOptGroupPro = document.createElement('optgroup');
            styleOptGroupPro.label = '⚡ Pro 스타일';
            window.skillData.proUIStyles.forEach((style, i) => {
                const option = document.createElement('option');
                option.value = `pro-${i}`;
                option.textContent = `⭐ ${style.nameKo} (${style.name})`;
                styleOptGroupPro.appendChild(option);
            });
            selectStyle.appendChild(styleOptGroupPro);
        }

        // Helper: Get palette by value
        function getPaletteByValue(val) {
            if (!val || val === '') return null;
            const [type, idx] = val.split('-');
            if (type === 'pro' && window.skillData) {
                const p = window.skillData.proColorPalettes[parseInt(idx)];
                return p ? {
                    name: p.type,
                    colors: [p.primary, p.secondary, p.cta, p.bg, p.text],
                    colorNames: ['Primary', 'Secondary', 'CTA', 'Background', 'Text'],
                    isPro: true,
                    border: p.border,
                    note: p.note
                } : null;
            }
            return colorPalettes[parseInt(idx)] || null;
        }

        // Helper: Get font by value
        function getFontByValue(val) {
            if (!val || val === '') return null;
            const [type, idx] = val.split('-');
            if (type === 'pro' && window.skillData) {
                const f = window.skillData.proFontPairings[parseInt(idx)];
                return f ? {
                    heading: f.heading,
                    body: f.body,
                    mood: f.mood,
                    googleUrl: f.cssImport ? f.cssImport.match(/url\('([^']+)'\)/)?.[1] : '',
                    cssImport: f.cssImport,
                    isPro: true
                } : null;
            }
            return fontPairings[parseInt(idx)] || null;
        }

        // Helper: Get style by value
        function getStyleByValue(val) {
            if (!val || val === '') return null;
            const [type, idx] = val.split('-');
            if (type === 'pro' && window.skillData) {
                const s = window.skillData.proUIStyles[parseInt(idx)];
                return s ? {
                    name: s.nameKo,
                    nameEn: s.name,
                    css: s.cssKeywords,
                    aiPrompt: s.aiPrompt,
                    isPro: true
                } : null;
            }
            return uiStyles[parseInt(idx)] || null;
        }

        // Palette preview
        selectPalette.addEventListener('change', () => {
            const palette = getPaletteByValue(selectPalette.value);
            if (palette) {
                selectedPalettePreview.innerHTML = palette.colors.map(c =>
                    `<div class="color-chip" style="background: ${c}"></div>`
                ).join('') + (palette.isPro ? '<span class="pro-indicator">PRO</span>' : '');
            } else {
                selectedPalettePreview.innerHTML = '';
            }
            updatePreview();
        });

        // Font preview
        selectFont.addEventListener('change', () => {
            const font = getFontByValue(selectFont.value);
            if (font) {
                selectedFontPreview.innerHTML = `
                    <div style="font-family: '${font.heading}', serif; font-size: 1.2rem; font-weight: 700;">${font.heading}</div>
                    <div style="font-family: '${font.body}', sans-serif; font-size: 0.9rem; color: var(--text-secondary);">${font.body}</div>
                    ${font.isPro ? '<span class="pro-indicator">PRO</span>' : ''}
                `;
            } else {
                selectedFontPreview.innerHTML = '';
            }
            updatePreview();
        });

        selectStyle.addEventListener('change', updatePreview);

        // Generate CSS
        generateBtn.addEventListener('click', generateCSS);
        copyCSSBtn.addEventListener('click', () => {
            copyToClipboard(generatedCSS.textContent);
        });

        function generateCSS() {
            const palette = getPaletteByValue(selectPalette.value);
            const font = getFontByValue(selectFont.value);
            const style = getStyleByValue(selectStyle.value);
            const includeDarkMode = document.getElementById('includeDarkMode').checked;
            const includeAnimations = document.getElementById('includeAnimations').checked;
            const includeResponsive = document.getElementById('includeResponsive').checked;

            let css = `/* ===== 자동 생성된 CSS ===== */\n/* 생성일: ${new Date().toLocaleString('ko-KR')} */\n`;
            if (palette?.isPro || font?.isPro || style?.isPro) {
                css += `/* 🏆 UI/UX Pro Max 스킬 데이터 포함 */\n`;
            }
            css += `\n`;

            // Color Variables
            if (palette) {
                css += `/* ===== 색상 변수 (${palette.name}) ===== */\n`;
                css += `:root {\n`;
                palette.colors.forEach((color, i) => {
                    const name = palette.colorNames[i].toLowerCase().replace(/\s+/g, '-');
                    css += `    --color-${name}: ${color};\n`;
                });
                css += `    --color-primary: ${palette.colors[0]};\n`;
                css += `    --color-secondary: ${palette.colors[1]};\n`;
                css += `    --color-accent: ${palette.colors[2]};\n`;
                css += `    --color-text: ${palette.colors[3]};\n`;
                css += `    --color-background: ${palette.colors[4]};\n`;
                if (palette.border) {
                    css += `    --color-border: ${palette.border};\n`;
                }
                css += `}\n\n`;
            }

            // Font Import
            if (font) {
                css += `/* ===== 폰트 (${font.heading} + ${font.body}) ===== */\n`;
                if (font.cssImport) {
                    css += `${font.cssImport}\n\n`;
                } else if (font.googleUrl) {
                    css += `@import url('${font.googleUrl}');\n\n`;
                }
                css += `:root {\n`;
                css += `    --font-heading: '${font.heading}', serif;\n`;
                css += `    --font-body: '${font.body}', sans-serif;\n`;
                css += `}\n\n`;
            }

            // Base Styles
            css += `/* ===== 기본 스타일 ===== */\n`;
            css += `* {\n    margin: 0;\n    padding: 0;\n    box-sizing: border-box;\n}\n\n`;
            css += `body {\n`;
            if (font) {
                css += `    font-family: var(--font-body);\n`;
            }
            if (palette) {
                css += `    background-color: var(--color-background);\n`;
                css += `    color: var(--color-text);\n`;
            }
            css += `    line-height: 1.6;\n`;
            css += `}\n\n`;

            // Headings
            if (font) {
                css += `h1, h2, h3, h4, h5, h6 {\n`;
                css += `    font-family: var(--font-heading);\n`;
                css += `    line-height: 1.2;\n`;
                css += `}\n\n`;
            }

            // UI Style
            if (style) {
                css += `/* ===== UI 스타일 (${style.name}) ===== */\n`;
                css += `.card {\n`;
                css += `    ${style.css}\n`;
                css += `    padding: 1.5rem;\n`;
                css += `    border-radius: 12px;\n`;
                css += `}\n\n`;
                if (style.aiPrompt) {
                    css += `/* AI 프롬프트: ${style.aiPrompt.substring(0, 100)}... */\n\n`;
                }
            }

            // Button Styles
            css += `/* ===== 버튼 스타일 ===== */\n`;
            css += `.btn {\n`;
            css += `    padding: 0.75rem 1.5rem;\n`;
            css += `    border: none;\n`;
            css += `    border-radius: 8px;\n`;
            css += `    font-size: 1rem;\n`;
            css += `    font-weight: 600;\n`;
            css += `    cursor: pointer;\n`;
            if (includeAnimations) {
                css += `    transition: all 0.2s ease;\n`;
            }
            css += `}\n\n`;

            css += `.btn-primary {\n`;
            if (palette) {
                css += `    background-color: var(--color-primary);\n`;
                css += `    color: white;\n`;
            }
            css += `}\n\n`;

            if (includeAnimations) {
                css += `.btn:hover {\n`;
                css += `    transform: translateY(-2px);\n`;
                css += `    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);\n`;
                css += `}\n\n`;
            }

            // Dark Mode
            if (includeDarkMode && palette) {
                css += `/* ===== 다크 모드 ===== */\n`;
                css += `@media (prefers-color-scheme: dark) {\n`;
                css += `    :root {\n`;
                css += `        --color-background: #1a1a2e;\n`;
                css += `        --color-text: #f5f5f5;\n`;
                css += `    }\n`;
                css += `}\n\n`;
            }

            // Animations
            if (includeAnimations) {
                css += `/* ===== 애니메이션 ===== */\n`;
                css += `@keyframes fadeIn {\n`;
                css += `    from { opacity: 0; transform: translateY(10px); }\n`;
                css += `    to { opacity: 1; transform: translateY(0); }\n`;
                css += `}\n\n`;
                css += `.fade-in {\n`;
                css += `    animation: fadeIn 0.3s ease forwards;\n`;
                css += `}\n\n`;
            }

            // Responsive
            if (includeResponsive) {
                css += `/* ===== 반응형 스타일 ===== */\n`;
                css += `.container {\n`;
                css += `    width: 100%;\n`;
                css += `    max-width: 1200px;\n`;
                css += `    margin: 0 auto;\n`;
                css += `    padding: 0 1rem;\n`;
                css += `}\n\n`;
                css += `@media (max-width: 768px) {\n`;
                css += `    .container {\n`;
                css += `        padding: 0 0.5rem;\n`;
                css += `    }\n`;
                css += `    \n`;
                css += `    h1 { font-size: 1.75rem; }\n`;
                css += `    h2 { font-size: 1.5rem; }\n`;
                css += `}\n`;
            }

            generatedCSS.textContent = css;
        }
    }

    // ===== Live Preview =====
    initLivePreview();

    function initLivePreview() {
        const deviceBtns = document.querySelectorAll('.device-btn');
        const templateSelect = document.getElementById('templateSelect');
        const previewFrame = document.getElementById('previewFrame');
        const previewContent = document.getElementById('previewContent');
        const openFullPreview = document.getElementById('openFullPreview');

        // Device switching
        deviceBtns.forEach(btn => {
            btn.addEventListener('click', () => {
                deviceBtns.forEach(b => b.classList.remove('active'));
                btn.classList.add('active');

                previewFrame.classList.remove('desktop', 'tablet', 'mobile');
                previewFrame.classList.add(btn.dataset.device);
            });
        });

        // Template change
        templateSelect.addEventListener('change', updatePreview);

        // Open in new window
        openFullPreview.addEventListener('click', () => {
            const html = generatePreviewHTML();
            const newWindow = window.open('', '_blank');
            newWindow.document.write(html);
            newWindow.document.close();
        });

        // Initial render
        updatePreview();
    }

    function updatePreview() {
        const previewContent = document.getElementById('previewContent');
        const template = document.getElementById('templateSelect').value;
        const paletteVal = document.getElementById('selectPalette').value;
        const fontVal = document.getElementById('selectFont').value;

        // Get palette (basic or pro)
        let palette = colorPalettes[0];
        if (paletteVal && paletteVal !== '') {
            const [type, idx] = paletteVal.split('-');
            if (type === 'pro' && window.skillData) {
                const p = window.skillData.proColorPalettes[parseInt(idx)];
                if (p) {
                    palette = {
                        colors: [p.primary, p.secondary, p.cta, p.bg, p.text]
                    };
                }
            } else {
                palette = colorPalettes[parseInt(idx)] || colorPalettes[0];
            }
        }

        // Get font (basic or pro)
        let font = fontPairings[0];
        if (fontVal && fontVal !== '') {
            const [type, idx] = fontVal.split('-');
            if (type === 'pro' && window.skillData) {
                const f = window.skillData.proFontPairings[parseInt(idx)];
                if (f) {
                    font = { heading: f.heading, body: f.body };
                }
            } else {
                font = fontPairings[parseInt(idx)] || fontPairings[0];
            }
        }

        const styles = `
            font-family: '${font.body}', sans-serif;
            background-color: ${palette.colors[4]};
            color: ${palette.colors[3]};
        `;

        let html = '';

        switch (template) {
            case 'landing':
                html = `
                    <div style="${styles}">
                        <div style="background: linear-gradient(135deg, ${palette.colors[0]}, ${palette.colors[1]}); padding: 4rem 2rem; text-align: center;">
                            <h1 style="font-family: '${font.heading}', serif; color: white; font-size: 2.5rem; margin-bottom: 1rem;">멋진 웹사이트에 오신 것을 환영합니다</h1>
                            <p style="color: rgba(255,255,255,0.9); font-size: 1.2rem; margin-bottom: 2rem;">최고의 서비스를 경험해보세요</p>
                            <button style="background: white; color: ${palette.colors[0]}; padding: 1rem 2rem; border: none; border-radius: 8px; font-size: 1rem; font-weight: 600; cursor: pointer;">시작하기</button>
                        </div>
                        <div style="padding: 3rem 2rem; display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1.5rem;">
                            <div style="background: white; padding: 1.5rem; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
                                <h3 style="font-family: '${font.heading}', serif; color: ${palette.colors[0]}; margin-bottom: 0.5rem;">✨ 기능 1</h3>
                                <p style="color: ${palette.colors[3]}; opacity: 0.8;">놀라운 기능을 제공합니다</p>
                            </div>
                            <div style="background: white; padding: 1.5rem; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
                                <h3 style="font-family: '${font.heading}', serif; color: ${palette.colors[0]}; margin-bottom: 0.5rem;">🚀 기능 2</h3>
                                <p style="color: ${palette.colors[3]}; opacity: 0.8;">빠르고 효율적입니다</p>
                            </div>
                            <div style="background: white; padding: 1.5rem; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">
                                <h3 style="font-family: '${font.heading}', serif; color: ${palette.colors[0]}; margin-bottom: 0.5rem;">💡 기능 3</h3>
                                <p style="color: ${palette.colors[3]}; opacity: 0.8;">쉽고 간편합니다</p>
                            </div>
                        </div>
                    </div>
                `;
                break;

            case 'card':
                html = `
                    <div style="${styles} padding: 2rem;">
                        <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1.5rem;">
                            <div style="background: white; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.1);">
                                <div style="height: 150px; background: linear-gradient(135deg, ${palette.colors[0]}, ${palette.colors[1]});"></div>
                                <div style="padding: 1.5rem;">
                                    <h3 style="font-family: '${font.heading}', serif; color: ${palette.colors[3]}; margin-bottom: 0.5rem;">카드 제목</h3>
                                    <p style="color: ${palette.colors[3]}; opacity: 0.7; margin-bottom: 1rem;">카드 내용이 여기에 들어갑니다. 간단한 설명을 작성하세요.</p>
                                    <button style="background: ${palette.colors[0]}; color: white; padding: 0.5rem 1rem; border: none; border-radius: 6px; cursor: pointer;">자세히 보기</button>
                                </div>
                            </div>
                            <div style="background: white; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.1);">
                                <div style="height: 150px; background: linear-gradient(135deg, ${palette.colors[1]}, ${palette.colors[2]});"></div>
                                <div style="padding: 1.5rem;">
                                    <h3 style="font-family: '${font.heading}', serif; color: ${palette.colors[3]}; margin-bottom: 0.5rem;">카드 제목</h3>
                                    <p style="color: ${palette.colors[3]}; opacity: 0.7; margin-bottom: 1rem;">카드 내용이 여기에 들어갑니다. 간단한 설명을 작성하세요.</p>
                                    <button style="background: ${palette.colors[1]}; color: white; padding: 0.5rem 1rem; border: none; border-radius: 6px; cursor: pointer;">자세히 보기</button>
                                </div>
                            </div>
                        </div>
                    </div>
                `;
                break;

            case 'dashboard':
                html = `
                    <div style="${styles}">
                        <div style="background: ${palette.colors[0]}; padding: 1rem 2rem; display: flex; justify-content: space-between; align-items: center;">
                            <h2 style="font-family: '${font.heading}', serif; color: white;">📊 대시보드</h2>
                            <div style="color: white;">환영합니다!</div>
                        </div>
                        <div style="padding: 2rem; display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem;">
                            <div style="background: white; padding: 1.5rem; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); border-left: 4px solid ${palette.colors[0]};">
                                <div style="color: ${palette.colors[3]}; opacity: 0.7; font-size: 0.9rem;">총 방문자</div>
                                <div style="font-family: '${font.heading}', serif; font-size: 2rem; color: ${palette.colors[0]};">12,345</div>
                            </div>
                            <div style="background: white; padding: 1.5rem; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); border-left: 4px solid ${palette.colors[1]};">
                                <div style="color: ${palette.colors[3]}; opacity: 0.7; font-size: 0.9rem;">매출</div>
                                <div style="font-family: '${font.heading}', serif; font-size: 2rem; color: ${palette.colors[1]};">₩2.5M</div>
                            </div>
                            <div style="background: white; padding: 1.5rem; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); border-left: 4px solid ${palette.colors[2]};">
                                <div style="color: ${palette.colors[3]}; opacity: 0.7; font-size: 0.9rem;">신규 가입</div>
                                <div style="font-family: '${font.heading}', serif; font-size: 2rem; color: ${palette.colors[2]};">234</div>
                            </div>
                            <div style="background: white; padding: 1.5rem; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); border-left: 4px solid ${palette.colors[0]};">
                                <div style="color: ${palette.colors[3]}; opacity: 0.7; font-size: 0.9rem;">성장률</div>
                                <div style="font-family: '${font.heading}', serif; font-size: 2rem; color: #22c55e;">+15%</div>
                            </div>
                        </div>
                    </div>
                `;
                break;

            case 'blog':
                html = `
                    <div style="${styles} padding: 2rem;">
                        <article style="max-width: 700px; margin: 0 auto; background: white; padding: 3rem; border-radius: 16px; box-shadow: 0 4px 20px rgba(0,0,0,0.1);">
                            <div style="color: ${palette.colors[0]}; font-size: 0.9rem; margin-bottom: 1rem;">📅 2026년 2월 5일</div>
                            <h1 style="font-family: '${font.heading}', serif; color: ${palette.colors[3]}; font-size: 2rem; margin-bottom: 1.5rem;">블로그 포스트 제목</h1>
                            <p style="color: ${palette.colors[3]}; opacity: 0.8; line-height: 1.8; margin-bottom: 1.5rem;">
                                이것은 블로그 포스트의 예시입니다. 선택한 색상과 폰트가 어떻게 적용되는지 확인해 보세요. 
                                콘텐츠는 읽기 편하고 시각적으로 매력적이어야 합니다.
                            </p>
                            <p style="color: ${palette.colors[3]}; opacity: 0.8; line-height: 1.8; margin-bottom: 1.5rem;">
                                좋은 타이포그래피와 색상 조합은 사용자 경험을 크게 향상시킵니다. 
                                여백을 적절히 사용하고, 대비를 잘 맞추는 것이 중요합니다.
                            </p>
                            <div style="display: flex; gap: 0.5rem; flex-wrap: wrap;">
                                <span style="background: ${palette.colors[4]}; color: ${palette.colors[0]}; padding: 0.25rem 0.75rem; border-radius: 20px; font-size: 0.85rem;">#디자인</span>
                                <span style="background: ${palette.colors[4]}; color: ${palette.colors[0]}; padding: 0.25rem 0.75rem; border-radius: 20px; font-size: 0.85rem;">#웹개발</span>
                                <span style="background: ${palette.colors[4]}; color: ${palette.colors[0]}; padding: 0.25rem 0.75rem; border-radius: 20px; font-size: 0.85rem;">#UI/UX</span>
                            </div>
                        </article>
                    </div>
                `;
                break;
        }

        previewContent.innerHTML = html;
    }

    function generatePreviewHTML() {
        const paletteVal = document.getElementById('selectPalette').value;
        const fontVal = document.getElementById('selectFont').value;
        const template = document.getElementById('templateSelect').value;

        // Get palette (basic or pro)
        let palette = colorPalettes[0];
        if (paletteVal && paletteVal !== '') {
            const [type, idx] = paletteVal.split('-');
            if (type === 'pro' && window.skillData) {
                const p = window.skillData.proColorPalettes[parseInt(idx)];
                if (p) {
                    palette = { colors: [p.primary, p.secondary, p.cta, p.bg, p.text] };
                }
            } else {
                palette = colorPalettes[parseInt(idx)] || colorPalettes[0];
            }
        }

        // Get font (basic or pro)
        let font = fontPairings[0];
        if (fontVal && fontVal !== '') {
            const [type, idx] = fontVal.split('-');
            if (type === 'pro' && window.skillData) {
                const f = window.skillData.proFontPairings[parseInt(idx)];
                if (f) font = { heading: f.heading, body: f.body };
            } else {
                font = fontPairings[parseInt(idx)] || fontPairings[0];
            }
        }

        return `
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>미리보기 - ${template}</title>
    <link href="${font.googleUrl}" rel="stylesheet">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
            font-family: '${font.body}', sans-serif; 
            background: ${palette.colors[4]}; 
            color: ${palette.colors[3]};
            line-height: 1.6;
        }
        h1, h2, h3 { font-family: '${font.heading}', serif; }
    </style>
</head>
<body>
    ${document.getElementById('previewContent').innerHTML}
</body>
</html>
        `;
    }

    // ===== Pro Palettes (Skill Data) =====
    function renderProPalettes() {
        const grid = document.getElementById('proPalettesGrid');
        if (!grid || !window.skillData) return;

        const { proColorPalettes } = window.skillData;

        grid.innerHTML = proColorPalettes.map(palette => `
            <div class="palette-card pro-palette">
                <div class="pro-badge">PRO</div>
                <div class="palette-colors">
                    <div class="color-swatch" style="background: ${palette.primary}" data-color="${palette.primary}" title="Primary"></div>
                    <div class="color-swatch" style="background: ${palette.secondary}" data-color="${palette.secondary}" title="Secondary"></div>
                    <div class="color-swatch" style="background: ${palette.cta}" data-color="${palette.cta}" title="CTA"></div>
                    <div class="color-swatch" style="background: ${palette.bg}" data-color="${palette.bg}" title="Background"></div>
                    <div class="color-swatch" style="background: ${palette.text}; ${palette.text.includes('F') ? 'border: 1px solid #ccc;' : ''}" data-color="${palette.text}" title="Text"></div>
                </div>
                <div class="palette-info">
                    <h3>${palette.type}</h3>
                    <p class="palette-note">${palette.note}</p>
                    <div class="palette-actions">
                        <button class="copy-css-btn" data-css=":root { --primary: ${palette.primary}; --secondary: ${palette.secondary}; --cta: ${palette.cta}; --bg: ${palette.bg}; --text: ${palette.text}; --border: ${palette.border}; }">
                            📋 CSS 변수 복사
                        </button>
                    </div>
                </div>
            </div>
        `).join('');

        // Add event listeners
        grid.querySelectorAll('.color-swatch').forEach(swatch => {
            swatch.addEventListener('click', () => copyToClipboard(swatch.dataset.color));
        });

        grid.querySelectorAll('.copy-css-btn').forEach(btn => {
            btn.addEventListener('click', () => copyToClipboard(btn.dataset.css));
        });
    }

    // ===== Pro Styles (Skill Data) =====
    function renderProStyles() {
        const grid = document.getElementById('proStylesGrid');
        if (!grid || !window.skillData) return;

        const { proUIStyles } = window.skillData;

        grid.innerHTML = proUIStyles.map(style => `
            <div class="style-card pro-style">
                <div class="pro-badge">PRO</div>
                <div class="style-preview" style="
                    background: ${style.colors.secondary};
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    min-height: 120px;
                    border-radius: 12px 12px 0 0;
                    position: relative;
                    overflow: hidden;
                ">
                    <div style="
                        background: ${style.colors.primary};
                        color: ${style.colors.accent};
                        padding: 1rem 2rem;
                        border-radius: 8px;
                        font-weight: 600;
                    ">${style.name}</div>
                </div>
                <div class="style-info">
                    <h3>${style.nameKo}</h3>
                    <p class="style-keywords">${style.keywords}</p>
                    <div class="style-best-for">
                        <strong>적합:</strong> ${style.bestFor.join(', ')}
                    </div>
                    <div class="style-actions">
                        <button class="copy-btn" data-text="${style.cssKeywords}" title="CSS 키워드 복사">
                            🎨 CSS
                        </button>
                        <button class="copy-btn" data-text="${style.aiPrompt}" title="AI 프롬프트 복사">
                            🤖 AI 프롬프트
                        </button>
                    </div>
                </div>
            </div>
        `).join('');

        // Add event listeners
        grid.querySelectorAll('.copy-btn').forEach(btn => {
            btn.addEventListener('click', () => copyToClipboard(btn.dataset.text));
        });
    }
});

